// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/screen-variants/ChatScreen.tsx": () => import("../components/mockups/screen-variants/ChatScreen.tsx"),
  "./components/mockups/screen-variants/GrowthScreen.tsx": () => import("../components/mockups/screen-variants/GrowthScreen.tsx"),
  "./components/mockups/screen-variants/OnboardingScreen.tsx": () => import("../components/mockups/screen-variants/OnboardingScreen.tsx"),
  "./components/mockups/home-variants/AmbientGradient.tsx": () => import("../components/mockups/home-variants/AmbientGradient.tsx"),
  "./components/mockups/home-variants/DarkGlass.tsx": () => import("../components/mockups/home-variants/DarkGlass.tsx"),
  "./components/mockups/home-variants/SurgicalLight.tsx": () => import("../components/mockups/home-variants/SurgicalLight.tsx")
};
